version: '3'

services:
  nacos:
    container_name: nacos-server
    image: nacos/nacos-server:v3.0.0
    restart: unless-stopped
    ports:
      - '8000:8080'
      - '8848:8848'
      - '9848:9848'
    environment:
      - MODE=standalone
      - JVM_XMS=256M
      - JVM_XMX=256M
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_IDENTITY_KEY=admin
      - NACOS_AUTH_IDENTITY_VALUE=123321cc
      - NACOS_AUTH_TOKEN=ZTA3YTM4NGI2N2ZlMGMzZjhiMTgwOWEzMWMxMDIxYTA3N2JhM2Y5OWNmMGNlNjBkMjQ3ZDkwMzY4NWJhZDU5Ng==
    networks:
      - common-bridge
    volumes:
      - nacos-data:/home/nacos/data
      - nacos-logs:/home/nacos/logs

volumes:
  nacos-data:
    name: nacos-data
  nacos-logs:
    name: nacos-logs

networks:
  common-bridge:
    name: common-bridge
    external: true
