version: '3'

services:
  nacos:
    container_name: nacos-server
    image: nacos/nacos-server:v3.0.0
    restart: unless-stopped
    ports:
      - '8000:8080'
      - '8848:8848'
      - '9848:9848'
    environment:
      - MODE=standalone
      - JVM_XMS=256M
      - JVM_XMX=256M
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_IDENTITY_KEY=admin
      - NACOS_AUTH_IDENTITY_VALUE=123321cc
      - NACOS_AUTH_TOKEN=ZTA3YTM4NGI2N2ZlMGMzZjhiMTgwOWEzMWMxMDIxYTA3N2JhM2Y5OWNmMGNlNjBkMjQ3ZDkwMzY4NWJhZDU5Ng==
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=nacos
      - MYSQL_SERVICE_DB_NAME=nacos 
      - MYSQL_SERVICE_DB_PARAM=useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    networks:
      - common-bridge
    volumes:
      - nacos-data:/home/nacos/data
      - nacos-logs:/home/nacos/logs
      - nacos-conf:/home/nacos/conf
    depends_on:
      - mysql
        # condition: service_healthy

  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123321cc
      MYSQL_DATABASE: test
      MYSQL_USER: lsx
      MYSQL_PASSWORD: 123321cc
    ports:
      - '3306:3306'
    volumes:
      -  mysql_data:/var/lib/mysql
    #healthcheck:
    # test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123321cc"]
    # interval: 5s
    # timeout: 10s
    # retries: 10
    networks:
      - common-bridge

volumes:
  nacos-data:
    name: nacos-data
  nacos-logs:
    name: nacos-logs
  nacos-conf:
    name: nacos-conf
  mysql_data:
    name: mysql_data

networks:
  common-bridge:
    name: common-bridge
    external: true
